import mobileMenu from './js/mobile-menu';
import themeToggle from './js/themeToggle';
import header from './js/header';
import seachcatalog from './js/seachcatalog';
import modalMovie from './js/modal_movie';
import scrollUp from './js/scroll-up';
import createWeekTrendsCatalog from './js/createTrends';
import './js/pagination';
import pagination from './js/pagination-catalog';
import { getDayMovieTrend } from './js/hero';
import modalTeam from './js/modal-team';
// import handleSearchFormSubmit from './js/seachcatalog';
